### ISSUE TITLE
RPC-020020009: 当前服务[com.ccbft.registry.service.HelloService:1.0]的地址[bolt://127.0.0.1:12200,]不可用,或指定的地址不在可用的地址列表中 

### ISSUE THREAD

**Issue by jamyy2000** [sofastack/sofa-rpc#1005]
### Your question

describe your question clearly

### Your scenes
RPC-020020009: 当前服务[com.ccbft.registry.service.HelloService:1.0]的地址[bolt://127.0.0.1:12200,]不可用,或指定的地址不在可用的地址列表中 
describe your use scenes (why need this feature)

Exception in thread "main" com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-020020009: 当前服务[com.ccbft.registry.service.HelloService:1.0]的地址[bolt://127.0.0.1:12200,]不可用,或指定的地址不在可用的地址列表中 
	at com.alipay.sofa.rpc.client.AbstractCluster.unavailableProviderException(AbstractCluster.java:500)
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:453)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:65)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:297)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at com.ccbft.registry.service.HelloService_proxy_0.sayHello(HelloService_proxy_0.java)
	at com.ccbft.registry.sub.StartClient.main(StartClient.java:28)
照着demo写了一个测试程序，客户端运行报以上错误，请问怎么解决？
### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.7.6
- JVM version (e.g. `java -version`): 1.8.0_241
- OS version (e.g. `uname -a`):win10
- Maven version: 3.6.3
- IDE version: 2020.3

**Comment by nick1889** [comment]
[https://github.com/sofastack/sofastack.tech/issues/445#issue-584189477](url)
