### ISSUE TITLE
启动教程中 client的main方法，发现无论调用server成功还是失败，client的main方法都不会关闭，有后台线程一直存在。

### ISSUE THREAD

**Issue by xuliguov5** [sofastack/sofa-rpc#1007]
### Describe the bug
Rpc-netty-client-worker-1-thread-1 RUNNABLE
RpcTaskScannerThread TIMED_WAITING
Log4j2-TF-16-AsyncLoggerConfig-1 TIMED_WAITING
并且 每创建一个ConsumerConfig 就会生成一个pc-netty-client-worker-1-thread-*
"Rpc-netty-client-worker-1-thread-1" #17 prio=5 os_prio=31 tid=0x00007fa3a6091800 nid=0xa403 runnable [0x00007000079b0000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000799981350> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000799982408> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000799981250> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"RpcTaskScannerThread" #16 daemon prio=5 os_prio=31 tid=0x00007fa3a6a7e800 nid=0x5903 waiting on condition [0x00007000078ad000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000079990db40> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Log4j2-TF-16-AsyncLoggerConfig-1" #15 daemon prio=5 os_prio=31 tid=0x00007fc2058c2800 nid=0xa603 waiting on condition [0x0000700010293000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007998e9798> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)
### Expected behavior
希望client调用成功或者调用完成时能自动关闭资源，或者调用特定函数关闭资源，
文档中的GracefulDestroyHook 钩子，不知道怎么使用。

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by xuliguov5** [comment]
上面描述的问题，在低版本3.0.2 会出现，升级为最高版本 就不存在了。
