### ISSUE TITLE
想请问一个独立服务在微服务框架中是否可以既做客户端又做服务端

### ISSUE THREAD

**Issue by itsmylovesdo** [sofastack/sofa-rpc#1021]
想请问一个独立服务在微服务框架中是否可以既做客户端调用客户端发布的服务接口，另一方面自己又做服务端发布服务。

现在的项目业务逻辑中存在这样的需求，一个服务可能需要既作为客户端， 又作为服务端。再尝试对这条服务同时做了客户端和服务端的配置以后，再其他客户端调用它的服务会出现报错。

Caused by: com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02306: Cannot get the service address of service [com.datasensa.ra.investmentadvisorsvc.service.IInvestmentAdvisorInfoService:1.0:user1], please check the registry log. 
	at com.alipay.sofa.rpc.client.AbstractCluster.noAvailableProviderException(AbstractCluster.java:426) ~[sofa-rpc-all-5.5.7.jar:5.5.7]
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:361) ~[sofa-rpc-all-5.5.7.jar:5.5.7]
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:64) ~[sofa-rpc-all-5.5.7.jar:5.5.7]
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:288) ~[sofa-rpc-all-5.5.7.jar:5.5.7]
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83) ~[sofa-rpc-all-5.5.7.jar:5.5.7]
	at com.datasensa.ra.investmentadvisorsvc.service.IInvestmentAdvisorInfoService_proxy_1.queryCustomerRecommendationInfo(IInvestmentAdvisorInfoService_proxy_1.java) ~[na:2.6.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]

感谢社区的帮助 希望可以找到答案

- SOFARPC version: 6.0.4
- JVM version (e.g. `java -version`): Java 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version: IntelliJ IDEA 2020.2.3 x64

**Comment by OrezzerO** [comment]
可以的,不确定你这边报错是什么问题.
