### ISSUE TITLE
Logging issue occurred during quick start

### ISSUE THREAD

**Issue by nobodyiam** [sofastack/sofa-rpc#1028]
### Describe the bug

When I followed the instructions of the [quick start](https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/) with log4j2 enabled, there will be many errors logged.

It looks like the `sofa-rpc-all-5.7.7.jar!/com/alipay/sofa/rpc/log/log4j2/log-conf.xml` file enables `AsyncLogger` but the required com.lmax:disruptor dependency is missing.

### Expected behavior

Either no error occurred or instruct the user to manually introduce the required dependency if log4j2 is used.

### Actual behavior

```
2021-04-12 16:38:52,569 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.async.AsyncLoggerConfig for element AsyncLogger: java.lang.NoClassDefFoundError: com/lmax/disruptor/EventHandler java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:136)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1000)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:940)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:932)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:551)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:287)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:627)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:304)
	at com.alipay.sofa.common.log.factory.Log4j2LoggerSpaceFactory.initialize(Log4j2LoggerSpaceFactory.java:111)
	at com.alipay.sofa.common.log.factory.Log4j2LoggerSpaceFactory.<init>(Log4j2LoggerSpaceFactory.java:75)
	at com.alipay.sofa.common.log.factory.LoggerSpaceFactory4Log4j2Builder.doBuild(LoggerSpaceFactory4Log4j2Builder.java:49)
	at com.alipay.sofa.common.log.factory.AbstractLoggerSpaceFactoryBuilder.build(AbstractLoggerSpaceFactoryBuilder.java:67)
	at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.createILoggerFactory(MultiAppLoggerSpaceManager.java:304)
	at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.doInit(MultiAppLoggerSpaceManager.java:115)
	at com.alipay.sofa.common.log.MultiAppLoggerSpaceManager.init(MultiAppLoggerSpaceManager.java:90)
	at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:97)
	at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:73)
	at com.alipay.sofa.common.log.LoggerSpaceManager.getLoggerBySpace(LoggerSpaceManager.java:79)
	at com.alipay.sofa.rpc.log.factory.RpcLoggerFactory.getLogger(RpcLoggerFactory.java:54)
	at com.alipay.sofa.rpc.log.MiddlewareLoggerImpl.<init>(MiddlewareLoggerImpl.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alipay.sofa.rpc.log.LoggerFactory.getLogger(LoggerFactory.java:57)
	at com.alipay.sofa.rpc.context.RpcRuntimeContext.<clinit>(RpcRuntimeContext.java:57)
	at com.alipay.sofa.rpc.config.AbstractIdConfig.<clinit>(AbstractIdConfig.java:40)
	at com.nobodyiam.java.sofa.rpc.QuickStartServer.main(QuickStartServer.java:11)
Caused by: java.lang.NoClassDefFoundError: com/lmax/disruptor/EventHandler
	at org.apache.logging.log4j.core.config.AbstractConfiguration.getAsyncLoggerConfigDelegate(AbstractConfiguration.java:206)
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.<init>(AsyncLoggerConfig.java:91)
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.createLogger(AsyncLoggerConfig.java:274)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.lmax.disruptor.EventHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
```

### Steps to reproduce

1. [quick start](https://www.sofastack.tech/projects/sofa-rpc/getting-started-with-rpc/) code
2. with pom.xml like the following:

```xml
  <properties>
    <log4j2.version>2.14.1</log4j2.version>
    <rpc.client.version>5.7.7</rpc.client.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.alipay.sofa</groupId>
        <artifactId>sofa-rpc-all</artifactId>
        <version>${rpc.client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-slf4j-impl</artifactId>
        <version>${log4j2.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>${log4j2.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>${log4j2.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.alipay.sofa</groupId>
      <artifactId>sofa-rpc-all</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>
  </dependencies>
```

### Environment

- SOFARPC version: 5.7.7
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by nobodyiam** [comment]
Is there any follow-up for this issue?

**Comment by JervyShi** [comment]
This is by design, the dynamic selection of logging framework is based on the user relies on a logging framework implementation to select the corresponding logging configuration, the user needs to import the full log4j2 dependencies if using log4j2.
