### ISSUE TITLE
com.alipay.remoting.util.FutureTaskNotCompleted

### ISSUE THREAD

**Issue by chancelee** [sofastack/sofa-rpc#1041]
[ERROR] - com.alipay.remoting.util.FutureTaskUtil.getFutureTaskResult(FutureTaskUtil.java:51) - Future task has not completed!
com.alipay.remoting.util.FutureTaskNotCompleted
	at com.alipay.remoting.util.RunStateRecordedFutureTask.getAfterRun(RunStateRecordedFutureTask.java:49) ~[bolt-1.5.3.jar:?]
	at com.alipay.remoting.util.FutureTaskUtil.getFutureTaskResult(FutureTaskUtil.java:43) [bolt-1.5.3.jar:?]
	at com.alipay.remoting.DefaultConnectionManager.getConnectionPool(DefaultConnectionManager.java:566) [bolt-1.5.3.jar:?]
	at com.alipay.remoting.DefaultConnectionManager.scan(DefaultConnectionManager.java:442) [bolt-1.5.3.jar:?]
	at com.alipay.remoting.rpc.RpcTaskScanner$1.run(RpcTaskScanner.java:56) [bolt-1.5.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by EvenLjj** [comment]
@chancelee 感谢提问，请问什么时候出现这种异常呢，描述的更清楚，有利于问题的排查。
***
@chancelee Thanks for asking, when does this exception occur. The description is clearer, which is conducive to solve.
