### ISSUE TITLE
偶现java.lang.NoClassDefFoundError: Could not initialize class com.alipay.remoting.serialization.SerializerManager

### ISSUE THREAD

**Issue by dannishushu** [sofastack/sofa-rpc#1116]
2021-10-26 16:13:58,632 ERROR [?#] [SOFA-SEV-BOLT-BIZ-12201-3-T10] DeserializationException occurred when process in RpcRequestProcessor, id=2478, deserializeLevel=DESERIALIZE_ALL
com.alipay.remoting.exception.DeserializationException: RPC-020050008: Serializer Not Found,type:[1].
        at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.deserializeContent(SofaRpcSerialization.java:274) ~[sofa-rpc-all-5.7.10.jar:5.7.10]
        at com.alipay.remoting.rpc.protocol.RpcRequestCommand.deserializeContent(RpcRequestCommand.java:144) ~[bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.RpcCommand.deserialize(RpcCommand.java:117) ~[bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.RpcCommand.deserialize(RpcCommand.java:138) ~[bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.deserializeRequestCommand(RpcRequestProcessor.java:267) [bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:142) [bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366) [bolt-1.5.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: RPC-020050008: Serializer Not Found,type:[1].
        at com.alipay.sofa.rpc.codec.SerializerFactory.getSerializer(SerializerFactory.java:87) ~[sofa-rpc-all-5.7.10.jar:5.7.10]
        at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.deserializeContent(SofaRpcSerialization.java:257) ~[sofa-rpc-all-5.7.10.jar:5.7.10]
        ... 9 more
2021-10-26 16:13:58,632 ERROR [?#] [SOFA-SEV-BOLT-BIZ-12201-3-T10] Serialize RpcResponseCommand failed when sendResponseIfNecessary in RpcRequestProcessor, id=2478
java.lang.NoClassDefFoundError: Could not initialize class com.alipay.remoting.serialization.SerializerManager
        at com.alipay.remoting.rpc.protocol.RpcResponseCommand.serializeContent(RpcResponseCommand.java:114) ~[bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.RpcCommand.serialize(RpcCommand.java:105) ~[bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.sendResponseIfNecessary(RpcRequestProcessor.java:162) [bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.deserializeRequestCommand(RpcRequestProcessor.java:274) [bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:142) [bolt-1.5.6.jar:?]
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366) [bolt-1.5.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

之前出现过这个现象，当时发现是hessian包冲突，已解决；现在环境现场已经排除了hessian包冲突的可能性。

环境现场bolt-1.5.6.jar也是正常存在的

暂时不知道是什么原因，偶现

**Comment by WindySummerF** [comment]
这个问题发生的原因可能是这样的:
测试环境中可能会使用Jenkins这种部署工具, 当进行项目部署的时候, lib包会先清空, 当lib包被清空后, 这个时候如果有rpc请求, server服务执行请求过程中会初始化一些hessian包中的类, 而这些类在之前的业务流程中还未被加载过, 所以需要从jar包加载, 此时lib包已经被清空, 导致ClassNotFound异常, 从而报以上异常

以上仅供参考.
