### ISSUE TITLE
多线程 调用sofa接口报异常

### ISSUE THREAD

**Issue by maqiubb** [sofastack/sofa-rpc#1457]
### Your question

java.util.NoSuchElementException: null
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285) ~[?:1.8.0_372]
	at java.util.ArrayDeque.pop(ArrayDeque.java:522) ~[?:1.8.0_372]
	at com.alipay.sofa.rpc.context.RpcInternalContext.popContext(RpcInternalContext.java:122) ~[sofa-rpc-all-5.8.3.jar:5.8.3]
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:100) ~[sofa-rpc-all-5.8.3.jar:5.8.3]
	at com.hundsun.lcpt.ta.pub.fina.api.IProductApi_proxy_0.countPrdRealtimeEstab(IProductApi_proxy_0.java) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor289.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at com.alipay.sofa.runtime.service.binding.JvmBindingAdapter$JvmServiceInvoker.doInvoke(JvmBindingAdapter.java:249) ~[runtime-sofa-boot-3.19.1.jar:3.19.1]
	at com.alipay.sofa.runtime.spi.service.ServiceProxy.invoke(ServiceProxy.java:40) ~[runtime-sofa-boot-3.19.1.jar:3.19.1]
	at com.alipay.sofa.runtime.service.binding.JvmBindingAdapter$JvmServiceInvoker.invoke(JvmBindingAdapter.java:160) ~[runtime-sofa-boot-3.19.1.jar:3.19.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.30.jar:5.3.30]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241) ~[spring-aop-5.3.30.jar:5.3.30]
	at com.sun.proxy.$Proxy120.countPrdRealtimeEstab(Unknown Source) ~[?:?]
	at com.hundsun.lcpt.ta.pub.fina.api.apifactory.PubFinaApiFactory.countPrdRealtimeEstab(PubFinaApiFactory.java:1746) ~[ta-fina-parameter-sofa-api.jar:?]

### Your scenes

![image](https://github.com/user-attachments/assets/ecaf0679-ebe7-43dc-895b-6e4d40d77cbf)
![image](https://github.com/user-attachments/assets/7d833035-4838-4364-b0c2-e78f3c0732f3)
![image](https://github.com/user-attachments/assets/24d19b49-cc65-40fc-9210-aeb3fe8b3264)

### Your advice

describe the advice or solution you'd like

### Environment
(sofa-rpc-all-5.8.3.jar:5.8.3)

**Comment by EvenLjj** [comment]
@maqiubb pls update to 5.8.5 to fix this issue, [release note](https://github.com/sofastack/sofa-rpc/releases/tag/v5.8.5).
