### ISSUE TITLE
关于sofa-rpc mvn编译出错

### ISSUE THREAD

**Issue by longsebo** [sofastack/sofa-rpc#494]
### Your question

我编译sofa-rpc报错，错误信息如下，我需要做什么处理不？
OperationException{statusCode=500, statusMessage='Internal Server Error', statusContent='CheckID "service:192.168.1.21:12201-null-50500" does not have associated TTL'}
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:211)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:198)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:193)
        at com.ecwid.consul.v1.ConsulClient.agentCheckPass(ConsulClient.java:258)
        at com.alipay.sofa.rpc.registry.consul.internal.TtlScheduler$ConsulHeartbeatServiceTask.run(TtlScheduler.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:26:13,347 SOFA-CheckServiceTimer-0-T1 ERROR [com.alipay.sofa.rpc.registry.consul.internal.TtlScheduler:run:113] - OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='CheckID "service:192.168.1.21:12200-null-50500" does not have associated TTL')
OperationException{statusCode=500, statusMessage='Internal Server Error', statusContent='CheckID "service:192.168.1.21:12200-null-50500" does not have associated TTL'}
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:211)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:198)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:193)
        at com.ecwid.consul.v1.ConsulClient.agentCheckPass(ConsulClient.java:258)
        at com.alipay.sofa.rpc.registry.consul.internal.TtlScheduler$ConsulHeartbeatServiceTask.run(TtlScheduler.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:26:13,349 SOFA-CheckServiceTimer-0-T1 ERROR [com.alipay.sofa.rpc.registry.consul.internal.TtlScheduler:run:113] - OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='CheckID "service:192.168.1.21:12200-null-50500" does not have associated TTL')
OperationException{statusCode=500, statusMessage='Internal Server Error', statusContent='CheckID "service:192.168.1.21:12200-null-50500" does not have associated TTL'}
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:211)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:198)
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:193)
        at com.ecwid.consul.v1.ConsulClient.agentCheckPass(ConsulClient.java:258)
        at com.alipay.sofa.rpc.registry.consul.internal.TtlScheduler$ConsulHeartbeatServiceTask.run(TtlScheduler.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 3.1.1
- JVM version (e.g. `java -version`):jdk8
- OS version (e.g. `uname -a`): win10
- Maven version:3.2.5
- IDE version:none

**Comment by longsebo** [comment]
SOFARPC version: 当前主干版本

**Comment by leizhiyuan** [comment]
编译的时候，

```
mvn clean  install -Dmaven.test.skip=true
```

看你这个应该是跑测试用例了。
