### ISSUE TITLE
Netty 4.1 堆外内存泄漏问题

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-rpc#592]
### Your question
内存溢出错误, netty 版本为 4.1.32.Final. 和 4.1.25.Final 都有问题. 改为4.0.24.Final 后没有这个问题.

2019-04-24 21:41:26,348 [SOFA-SEV-REST-BIZ-8341-4-T2] WARN  com.alipay.sofa.rpc.server.rest.SofaRestRequestHandler- Exception caught by request handler
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658247, max: 257425408)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:655)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:610)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:769)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:745)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at java.lang.Thread.run(Thread.java:745)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.5.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
Hi，有分析过堆外内存里的数据吗？ 或者重现的场景可以详细描述下吗？

**Comment by OrezzerO** [comment]
我尝试上传一个可以重现的项目

**Comment by OrezzerO** [comment]
https://github.com/OrezzerO/sofa-oom     设置 -Xms256m -Xmx256m   项目里面只有一个接口, 用大的 payload 请求这个接口,应该很容易就 oom 了

**Comment by ujjboy** [comment]
我明天试试。

**Comment by ujjboy** [comment]
@OrezzerO  已重现，不过看起来可能是 resteasy 的问题，并不是 netty 的问题。我会继续分析。

**Comment by ujjboy** [comment]
@OrezzerO #593 你可以试试下这个PR里的修复代码，看还能复现吗？

**Comment by OrezzerO** [comment]
@ujjboy 我试一下

**Comment by OrezzerO** [comment]
@ujjboy  已确认,不泄露了. 看了你改的代码, 这样子resteasy 也必须使用升netty-all 4.1.25 了.  实际上我们使用的时候, 有一些组件(就是指CAT ) 也有使用 netty 4.1.x 内存泄漏的问题, 所以我们在具体使用的时候,用的还是 netty 4.0.x .   所以,个人建议先别把  PR 和进去, 毕竟好像就我们一家再用rest....

**Comment by khotyn** [comment]
@OrezzerO 我们自己也有在用 REST，😂

**Comment by OrezzerO** [comment]
@khotyn  那这个 oom 你们内部是什么情况? joy

**Comment by ujjboy** [comment]
@OrezzerO 嗯，我也注意到了 `new ByteBufInputStream(buf, true);` 这个地方在 netty-4.0.x 里是不存在的，这是个4.1 和 4.0 不兼容的点。 我这边再看下有没有其他办法。 

内部的话目前看这个问题也是一直存在的，只不过用的堆内分配，会被fullgc回收掉。

**Comment by OrezzerO** [comment]
@ujjboy  是否可以提供一下 netty 使用内存分配的方案?

**Comment by zonghaishang** [comment]
`com.alipay.sofa.rpc.server.rest.SofaRestRequestHandler` 读完报文后，没有关闭`buf`，`channelRead0`需要自己关闭。`org.jboss.resteasy.plugins.server.netty.RequestHandler#channelRead0` 对应的实现自己关闭了

在5.6.0中会修复。

**Comment by Serenagirl** [comment]
请问下怎么修改netty版本？
