### ISSUE TITLE
Extension com.alipay.sofa.rpc.codec.protobuf.ProtostuffSerializer of extensible com.alipay.sofa.rpc.codec.Serializer is disabled, 

### ISSUE THREAD

**Issue by mailfly** [sofastack/sofa-rpc#759]
when using sofa bolt ,will encounter below issue:
2019-09-09 17:22:22,407 [SOFA-SEV-BOLT-BIZ-12200-8-T1] WARN  
com.alipay.sofa.common.log- 
Extension com.alipay.sofa.rpc.codec.protobuf.ProtostuffSerializer of extensible com.alipay.sofa.rpc.codec.Serializer is disabled, 
cause by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: java.lang.ClassNotFoundException: 
com.alipay.sofa.rpc.codec.protobuf.ProtostuffSerializer		
at com.alipay.sofa.rpc.common.utils.ClassUtils.forName(ClassUtils.java:59)		
at com.alipay.sofa.rpc.ext.ExtensionLoader.readLine(ExtensionLoader.java:210)	

check the code as below, maybe some code type issue, the package name is wrong,please check:

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by mailfly** [comment]
protostuff=com.alipay.sofa.rpc.codec.protobuf.ProtostuffSerializer
but the true package name is: com.alipay.sofa.rpc.codec.protostuff.ProtostuffSerializer

**Comment by mailfly** [comment]
see pr fixed path error #758
