### ISSUE TITLE
ClassNotFoundException: com.alipay.sofa.infra.log.space.SofaBootLogSpaceIsolationInit

### ISSUE THREAD

**Issue by opjk** [sofastack/sofa-rpc#769]
### Your question

2019-09-23 14:45:49.969 ERROR 16357 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: com/alipay/sofa/infra/log/space/SofaBootLogSpaceIsolationInit
        at com.alipay.sofa.rpc.boot.SofaBootRpcInitializer.initStarterLog(SofaBootRpcInitializer.java:65)
        at com.alipay.sofa.rpc.boot.SofaBootRpcInitializer.initialize(SofaBootRpcInitializer.java:44)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at com.gridnt.AppServerStarter.main(AppServerStarter.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.infra.log.space.SofaBootLogSpaceIsolationInit
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 14 common frames omitted

### Your scenes

sofaboot 从3.1.5 升级到3.2.0时，出现上述问题。

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by opjk** [comment]
compile group: "com.alipay.sofa", name: "runtime-sofa-boot-starter", version: "${sofaVersion}"
    compile group: "com.alipay.sofa", name: "infra-sofa-boot-starter", version: "${sofaVersion}"
    compile group: "com.alipay.sofa", name: "rpc-sofa-boot-starter", version: "6.0.4"

sofaVersion 3.1.5,升级为3.2.0
