### ISSUE TITLE
When integrate with dubbo 2.6.7, shutdown hook does not work

### ISSUE THREAD

**Issue by khotyn** [sofastack/sofa-rpc#804]
### Describe the bug

When integrate with dubbo 2.6.7, shutdown hook does not work

```
Exception in thread "SOFA-RPC-ShutdownHook" java.lang.NoSuchMethodError: com.alibaba.dubbo.config.ProtocolConfig.destory()V
	at com.alipay.sofa.rpc.bootstrap.dubbo.DubboSingleton.destroyAll(DubboSingleton.java:65)
	at com.alipay.sofa.rpc.bootstrap.dubbo.DubboSingleton$1.preDestroy(DubboSingleton.java:40)
	at com.alipay.sofa.rpc.context.RpcRuntimeContext.destroy(RpcRuntimeContext.java:140)
	at com.alipay.sofa.rpc.context.RpcRuntimeContext.access$100(RpcRuntimeContext.java:51)
	at com.alipay.sofa.rpc.context.RpcRuntimeContext$1.run(RpcRuntimeContext.java:108)
	at java.lang.Thread.run(Thread.java:745)
```

### Environment

- SOFARPC version: 5.6.1
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
dubbo 自己的问题。在2.6.7中将这个方法删除了。

在2.8.4中又加回去了。不做兼容，建议用户升级。
