### ISSUE TITLE
SimpleMapSerializer 5.6.1 is not compatible with 5.5.9 serialized map when deserialized

### ISSUE THREAD

**Issue by HuangSheng** [sofastack/sofa-rpc#805]
### Describe the bug

```
com.alipay.sofa.rpc.core.exception.SofaRpcException: com.alipay.remoting.exception.DeserializationException: Server deserialize request exception! the address is 127.0.0.1:10012, id=3, serverSide=true
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.convertToRpcException(BoltClientTransport.java:342) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:251) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.AbstractCluster.doSendMsg(AbstractCluster.java:517) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.AbstractCluster.sendMsg(AbstractCluster.java:488) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.ConsumerInvoker.invoke(ConsumerInvoker.java:60) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.sofatracer.ConsumerTracerFilter.invoke(ConsumerTracerFilter.java:66) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.RpcReferenceContextFilter.invoke(RpcReferenceContextFilter.java:80) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.ConsumerExceptionFilter.invoke(ConsumerExceptionFilter.java:37) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:262) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.AbstractCluster.filterChain(AbstractCluster.java:481) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:66) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:288) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83) ~[sofa-rpc-all-5.5.9.jar:5.5.9]
	at com.gbanker.sofa.bootstrap.BoltAopClientProxyInvoker.invoke(BoltAopClientProxyInvoker.java:61) ~[rpc-sofa-ext-1.0.0-SNAPSHOT.jar:na]
	at com.alipay.sofa.server.demo.service.AnnotionService_proxy_0.testGetResult(AnnotionService_proxy_0.java) [na:na]
	at com.gbanker.access.finance.controller.user.DemoController.testDemo(DemoController.java:63) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:685) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
-------------------------------

2019-11-20 14:14:40,826 ERROR [RpcRequestProcessor#270] [SOFA-SEV-BOLT-BIZ-10012-6-T20] DeserializationException occurred when process in RpcRequestProcessor, id=1024, deserializeLevel=DESERIALIZE_ALL
com.alipay.remoting.exception.DeserializationException: Exception caught when deserialize header of rpc request command!
	at com.alipay.remoting.rpc.protocol.RpcRequestCommand.deserializeHeader(RpcRequestCommand.java:113)
	at com.alipay.remoting.rpc.RpcCommand.deserialize(RpcCommand.java:116)
	at com.alipay.remoting.rpc.RpcCommand.deserialize(RpcCommand.java:138)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.deserializeRequestCommand(RpcRequestProcessor.java:267)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:142)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NegativeArraySizeException: null
	at com.alipay.sofa.rpc.codec.bolt.SimpleMapSerializer.decode(SimpleMapSerializer.java:112)
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.deserializeHeader(SofaRpcSerialization.java:151)
	at com.alipay.remoting.rpc.protocol.RpcRequestCommand.deserializeHeader(RpcRequestCommand.java:109)
	... 8 common frames omitted
```

在使用5.5.9版本的SOFARPC客户端调用使用了5.6.1版本的SOFARPC服务端时，如果使用注册中心，则没问题，如果使用直连方式，则出现序列化异常

通过看源码发现在 SimpleMapSerializer 的序列化和反序列化代码中两个版本不一致，主要体现在如果需要序列化的字符串为null，5.5.9版本会write一个-1，如果是5.5.9版本的反序列化会判断是否小于0，而5.6.1版本的反序列化没有做小于0判断

5.6.1版本的 反序列化代码
![image](https://user-images.githubusercontent.com/2976373/69216781-f967e100-0ba7-11ea-91af-d2fac0c8a0ad.png)

5.5.9版本的 序列化代码
![image](https://user-images.githubusercontent.com/2976373/69216838-1dc3bd80-0ba8-11ea-87cb-9fd1070f2f00.png)

![image](https://user-images.githubusercontent.com/2976373/69216825-14d2ec00-0ba8-11ea-97b6-299bd6ac1ae7.png)

5.5.9版本的 反序列化代码
![image](https://user-images.githubusercontent.com/2976373/69216851-2a481600-0ba8-11ea-890b-0f21278ee1f9.png)

![image](https://user-images.githubusercontent.com/2976373/69216866-32a05100-0ba8-11ea-991b-08e4281de776.png)

### Environment

- SOFARPC version: 5.6.1
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by HuangSheng** [comment]
对比了一下两个版本的代码发现5.6.1版本的代码中还保留有5.5.9版本的readString方法，不知为什么不用该方法而自己重写了一遍？是为了提升性能吗？

**Comment by leizhiyuan** [comment]
@NeGnail @zonghaishang  看下呢。是不是decode时候，没有正确处理兼容的场景。读到-1的时候，也要能正常处理。
