### ISSUE TITLE
Register jaxrs service error

### ISSUE THREAD

**Issue by dagou** [sofastack/sofa-rpc#878]
ERROR main                             com.alipay.sofa.rpc.server.rest.RestServer - Register jaxrs service error
java.lang.RuntimeException: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path:

**Comment by leizhiyuan** [comment]
麻烦提供下具体的错误栈，如果有复现的demo更好

**Comment by dagou** [comment]
2020-03-10 13:51:19,566 INFO  main                             com.alipay.sofa.rpc.server.rest.RestServer - Start the http rest server at port 8341
2020-03-10 13:51:19,567 INFO  main                             com.alipay.sofa.rpc.server.rest.RestServer - Register jaxrs service to base url http://0.0.0.0:8341
2020-03-10 13:51:19,747 ERROR main                             com.alipay.sofa.rpc.server.rest.RestServer - Register jaxrs service error
java.lang.RuntimeException: RESTEASY003130: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path: com.csii.useraccountservice.interfaces.apis.UserRealNameAuthService_proxy_11 implements:  com.csii.useraccountservice.interfaces.apis.UserRealNameAuthService
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:183)
	at com.alipay.sofa.rpc.server.rest.SofaResourceMethodRegistry.addResourceFactory(SofaResourceMethodRegistry.java:51)
	at com.alipay.sofa.rpc.server.rest.RestServer.registerProcessor(RestServer.java:213)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.doExport(DefaultProviderBootstrap.java:177)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.export(DefaultProviderBootstrap.java:106)
	at com.alipay.sofa.rpc.config.ProviderConfig.export(ProviderConfig.java:531)
	at com.alipay.sofa.rpc.boot.runtime.adapter.RpcBindingAdapter.outBinding(RpcBindingAdapter.java:103)
	at com.alipay.sofa.rpc.boot.runtime.adapter.RpcBindingAdapter.outBinding(RpcBindingAdapter.java:46)
	at com.alipay.sofa.runtime.service.component.ServiceComponent.activateBinding(ServiceComponent.java:157)
	at com.alipay.sofa.runtime.service.component.ServiceComponent.activate(ServiceComponent.java:126)
	at com.alipay.sofa.runtime.component.impl.ComponentManagerImpl.doRegister(ComponentManagerImpl.java:160)
	at com.alipay.sofa.runtime.component.impl.ComponentManagerImpl.register(ComponentManagerImpl.java:116)
	at com.alipay.sofa.runtime.spring.factory.ServiceFactoryBean.doAfterPropertiesSet(ServiceFactoryBean.java:73)
	at com.alipay.sofa.runtime.spring.factory.AbstractContractFactoryBean.afterPropertiesSet(AbstractContractFactoryBean.java:99)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1830)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1767)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:828)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.csii.useraccountservice.UserAccountServiceApplication.main(UserAccountServiceApplication.java:31)

**Comment by leizhiyuan** [comment]
UserRealNameAuthService 这个接口上要打@Path注解

**Comment by dagou** [comment]
我用 企业版的&nbsp; 不需要打@path注解。。开源版的需要？




------------------&nbsp;Original&nbsp;------------------

**Comment by leizhiyuan** [comment]
> 我用 企业版的&nbsp; 不需要打@path注解。。开源版的需要？
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From:&nbsp;"Lei Zhiyuan"<notifications@github.com&gt;; Date:&nbsp;Tue, Mar 10, 2020 05:45 PM To:&nbsp;"sofastack/sofa-rpc"<sofa-rpc@noreply.github.com&gt;; Cc:&nbsp;"朱正伟"<tourist_chu@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject:&nbsp;Re: [sofastack/sofa-rpc] Register jaxrs service error (#878) UserRealNameAuthService 这个接口上要打@path注解 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

实现的机制不太一样。可以咨询商业售后同学。

**Comment by OrezzerO** [comment]
No further information, close issue. You can open it ,if necessary @dagou
