### ISSUE TITLE
RPC service call reports serialization exception

### ISSUE THREAD

**Issue by leijian0128** [sofastack/sofa-rpc#913]
### Your question

消费者消费时报错：Caused by: com.alipay.remoting.exception.SerializationException: RPC-020050008: 未找到 Serializer,type:[1]. 

### Your scenes

Caused by: com.alipay.remoting.exception.SerializationException: RPC-020050008: 未找到 Serializer,type:[1]. 
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.serializeContent(SofaRpcSerialization.java:198) ~[sofa-rpc-all-5.6.5.jar:5.6.5]
	at com.alipay.remoting.rpc.protocol.RpcRequestCommand.serializeContent(RpcRequestCommand.java:124) ~[bolt-1.5.6.jar:na]
	at com.alipay.remoting.rpc.RpcCommand.serialize(RpcCommand.java:105) ~[bolt-1.5.6.jar:na]
	at com.alipay.remoting.rpc.RpcRemoting.toRemotingCommand(RpcRemoting.java:354) ~[bolt-1.5.6.jar:na]
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:179) ~[bolt-1.5.6.jar:na]
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:64) ~[bolt-1.5.6.jar:na]
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:355) ~[bolt-1.5.6.jar:na]
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.doInvokeSync(BoltClientTransport.java:279) ~[sofa-rpc-all-5.6.5.jar:5.6.5]
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:252) ~[sofa-rpc-all-5.6.5.jar:5.6.5]
	... 91 common frames omitted
Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: RPC-020050008: 未找到 Serializer,type:[1]. 
	at com.alipay.sofa.rpc.codec.SerializerFactory.getSerializer(SerializerFactory.java:85) ~[sofa-rpc-all-5.6.5.jar:5.6.5]
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.serializeContent(SofaRpcSerialization.java:193) ~[sofa-rpc-all-5.6.5.jar:5.6.5]
	... 99 common frames omitted

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.6.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
你有设置了一些特殊的自定义设置吗?
