### ISSUE TITLE
h2  com.alipay.sofa.rpc.core.exception.SofaRpcException:channel has been closed

### ISSUE THREAD

**Issue by xiaoming2624** [sofastack/sofa-rpc#951]
### Describe the bug
Protocol :h2
quote SOFARPC: 5.7.3  java file name-Http2ServerChannelHandler.java
tps:10

error:
2020-06-11 16:26:44,720 ERROR org.apache.juli.logging.DirectJDKLog.log:175  Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.alipay.sofa.rpc.core.exception.SofaRpcException: com.alipay.sofa.rpc.core.exception.SofaRpcException: Channel 127.0.0.1:49677 -> 127.0.0.1:12200 has been closed, remove future when channel inactive.] with root cause
com.alipay.sofa.rpc.core.exception.SofaRpcException: Channel 127.0.0.1:49677 -> 127.0.0.1:12200 has been closed, remove future when channel inactive.
	at com.alipay.sofa.rpc.transport.http.Http2ClientChannelHandler.channelInactive(Http2ClientChannelHandler.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:427)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1050)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)

### Environment
- SOFARPC: 5.6.5
- java -version:1.8
- Maven version:3
- IDE version:2019

**Comment by leizhiyuan** [comment]
服务端端口是12200？这个应该是bolt的端口，不是h2的吧？是不是配置错了

**Comment by xiaoming2624** [comment]
because report log error,I add bytebuf release 
![image](https://user-images.githubusercontent.com/26619622/85214471-73aa4f00-b39d-11ea-92fc-c218174c47fc.png)

now notes it, It's ready
but log error, I closed it.
